# Generated by Django 5.1.7 on 2025-04-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_disposableincomespending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposableincomebudget',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
