# Generated by Django 5.1.7 on 2025-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_disposableincomebudget_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='repeat_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='repeated',
            field=models.CharField(choices=[('NEVER', 'Never'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NEVER'),
        ),
        migrations.AlterField(
            model_name='income',
            name='repeated',
            field=models.CharField(choices=[('NEVER', 'Never'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NEVER'),
        ),
    ]
