# Generated by Django 5.1.7 on 2025-05-02 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_income_repeat_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disposableincomebudget',
            unique_together={('owner', 'date')},
        ),
    ]
