# Generated by Django 5.1.7 on 2025-05-13 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_disposableincomebudget_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposableincomebudget',
            options={'ordering': ['-date'], 'verbose_name': 'Disposable Income Budget', 'verbose_name_plural': 'Disposable Income Budgets'},
        ),
        migrations.AlterModelOptions(
            name='disposableincomespending',
            options={'ordering': ['-date'], 'verbose_name': 'Disposable Income Spending', 'verbose_name_plural': 'Disposable Income Spendings'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar $'), ('EUR', 'Euro €'), ('JPY', 'Japanese Yen ¥'), ('GBP', 'British Pound £'), ('AUD', 'Australian Dollar A$'), ('CAD', 'Canadian Dollar C$'), ('CHF', 'Swiss Franc CHF'), ('CNY', 'Chinese Yuan ¥'), ('HKD', 'Hong Kong Dollar HK$'), ('INR', 'Indian Rupee ₹')], default='GBP', help_text='Three-letter ISO currency code.'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disposableincomebudget',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Budget amount in pence.'),
        ),
        migrations.AlterField(
            model_name='disposableincomebudget',
            name='date',
            field=models.DateTimeField(help_text='First day of the month this budget applies to.'),
        ),
        migrations.AlterField(
            model_name='disposableincomebudget',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposable_income_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disposableincomespending',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount spent in pence.'),
        ),
        migrations.AlterField(
            model_name='disposableincomespending',
            name='date',
            field=models.DateTimeField(help_text='Date and time of the spending entry.'),
        ),
        migrations.AlterField(
            model_name='disposableincomespending',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposable_income_spending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disposableincomespending',
            name='title',
            field=models.CharField(help_text='Short description of the expenditure.', max_length=100),
        ),
    ]
