# Generated by Django 5.1.7 on 2025-05-13 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_disposableincomebudget_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposableincomebudget',
            options={'ordering': ['-date'], 'verbose_name': 'Disposable Income Budget'},
        ),
        migrations.AlterModelOptions(
            name='disposableincomespending',
            options={'ordering': ['-date'], 'verbose_name': 'Disposable Income Spending'},
        ),
        migrations.AlterModelOptions(
            name='expenditure',
            options={'ordering': ['-date'], 'verbose_name': 'Expenditure', 'verbose_name_plural': 'Expenditures'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in pence (e.g., £12.99 = 1299).'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateTimeField(help_text='Date and time the expenditure applies to.'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='repeat_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Used to group related repeated entries.', null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='repeated',
            field=models.CharField(choices=[('NEVER', 'Never'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NEVER', help_text='Repetition frequency (e.g., NEVER, MONTHLY).'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='title',
            field=models.CharField(help_text='Name or label for this expenditure.', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('SAVING', 'Savings'), ('INVESTMENT', 'Investment')], default='BILL', help_text='Type/category of expenditure.'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.PositiveIntegerField(help_text='Income amount in pence (e.g., £1200 = 120000).'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(help_text='Date the income applies to.'),
        ),
        migrations.AlterField(
            model_name='income',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='income',
            name='repeat_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID for grouping repeated incomes (used for bulk updates/deletes).', null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='repeated',
            field=models.CharField(choices=[('NEVER', 'Never'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NEVER', help_text='Repetition frequency of the income entry.'),
        ),
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(help_text='Short label for this income source.', max_length=100),
        ),
    ]
