# Generated by Django 5.1.7 on 2025-05-26 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_disposableincomebudget_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposableincomebudget',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Budget amount in pence.', validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='disposableincomespending',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount spent in pence.', validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='disposableincomespending',
            name='title',
            field=models.CharField(help_text='Short description of the expenditure.', max_length=50),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount in pence (e.g., £12.99 = 1299).', validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='title',
            field=models.CharField(help_text='Name or label for this expenditure.', max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.PositiveIntegerField(help_text='Income amount in pence (e.g., £1200 = 120000).', validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(help_text='Short label for this income source.', max_length=50),
        ),
    ]
